# frozen_string_literal: true

# app/lib/integrations/field_pulse/v1/customers.rb
module Integrations
  module FieldPulse
    module V1
      module Customers
        # call FieldPulse API for a specific customer
        # fp_client.customer()
        #   fp_customer_id: (Integer)
        def customer(fp_customer_id)
          reset_attributes
          @result = {}

          if fp_customer_id.to_i.zero?
            @message = 'Invalid FieldPulse customer id'
            @success = false
            return @result
          end

          fieldpulse_request(
            body:                  nil,
            error_message_prepend: 'Integrations::FieldPulse::V1::Customers.customer',
            method:                'get',
            params:                nil,
            default_result:        @result,
            url:                   "customers/#{fp_customer_id}"
          )

          @result
        end
        # example FieldPulse response
        # {
        #   error:    false,
        #   response: {
        #     id:                                    7500746,
        #     company_id:                            114785,
        #     mongo_id:                              nil,
        #     email:                                 'janesmith@abccompanyinc.com',
        #     phone:                                 '214 555 5555',
        #     city:                                  'Dallas',
        #     state:                                 'TX',
        #     notes:                                 nil,
        #     address_1:                             '8144 Walnut Hill Lane',
        #     address_2:                             nil,
        #     cuid:                                  1002,
        #     first_name:                            'Jane',
        #     middle_name:                           nil,
        #     last_name:                             'Smith',
        #     company_name:                          'ABC Company',
        #     zip_code:                              '75231',
        #     searchable:                            nil,
        #     sort_key:                              nil,
        #     status:                                nil,
        #     has_different_billing_address:         false,
        #     alt_email:                             nil,
        #     phone_e164:                            nil,
        #     qbo_id:                                nil,
        #     title:                                 nil,
        #     suffix:                                nil,
        #     alt_phone:                             nil,
        #     billing_address_1:                     nil,
        #     billing_address_2:                     nil,
        #     billing_city:                          nil,
        #     billing_state:                         nil,
        #     fax:                                   nil,
        #     skype:                                 nil,
        #     assigned_to:                           nil,
        #     billing_zip_code:                      nil,
        #     secondary_first_name:                  nil,
        #     secondary_last_name:                   nil,
        #     secondary_email:                       nil,
        #     secondary_phone:                       nil,
        #     use_company_name:                      nil,
        #     dial_phone:                            nil,
        #     mobile_phone:                          nil,
        #     website:                               nil,
        #     qbo_sync_token:                        nil,
        #     last_qbo_sync:                         nil,
        #     created_at:                            '2024-09-12 19:31:12',
        #     updated_at:                            '2024-09-12 19:31:12',
        #     deleted_at:                            nil,
        #     parent_id:                             nil,
        #     postal_code:                           nil,
        #     alt_first_name:                        nil,
        #     alt_last_name:                         nil,
        #     lead_source:                           nil,
        #     service_address_1:                     nil,
        #     service_address_2:                     nil,
        #     service_address_city:                  nil,
        #     service_address_state:                 nil,
        #     service_address_zip_code:              nil,
        #     job_notes:                             nil,
        #     account_type:                          'company',
        #     parent_id_previous:                    nil,
        #     address1:                              nil,
        #     xero_id:                               nil,
        #     is_sync:                               nil,
        #     notes_old:                             nil,
        #     different_billing_address:             nil,
        #     xero_group_id:                         nil,
        #     dev_qbo:                               nil,
        #     source:                                nil,
        #     secondar_last_name:                    nil,
        #     sync_status:                           nil,
        #     xero_guid:                             nil,
        #     display_name:                          'ABC Company',
        #     uuid:                                  '6369bfba-d942-41cc-954c-1ed76de8d673',
        #     xero_updated_date_utc:                 nil,
        #     country_code:                          nil,
        #     country_phone_code:                    nil,
        #     has_valid_phone:                       nil,
        #     alt_phone_e164:                        nil,
        #     secondary_phone_e164:                  nil,
        #     searchable_number:                     nil,
        #     phone_validation_message:              nil,
        #     lead_source_id:                        nil,
        #     servicerocketpro_id:                   nil,
        #     service_titan_id:                      nil,
        #     pipeline_status_id:                    nil,
        #     next_steps:                            '',
        #     qbd_id:                                nil,
        #     qbd_edit_sequence:                     nil,
        #     merged_customer_id:                    nil,
        #     pipeline_status_updated_at:            nil,
        #     mailchimp_contact_id:                  nil,
        #     is_tax_exempt:                         false,
        #     qbo_tax_exempt_reason:                 nil,
        #     search_text:                           "'abc':2 'compani':3 'jane':4 'janesmith@abccompanyinc.com':1 'smith':5",
        #     import_id:                             nil,
        #     qbd_fullname:                          nil,
        #     qbd_addr_company_name:                 false,
        #     qbd_addr_first_last_name:              false,
        #     nicejob_id:                            nil,
        #     marketing360_id:                       nil,
        #     qbo_is_project:                        false,
        #     asset_display_settings:                nil,
        #     next_sync_allowed_at:                  nil,
        #     sync_version:                          nil,
        #     job_display_settings:                  nil,
        #     default_invoice_due_date:              nil,
        #     default_estimate_expiration_date:      nil,
        #     is_phone_notification_subscribed:      true,
        #     is_email_notification_subscribed:      true,
        #     billing_address_3:                     nil,
        #     billing_address_4:                     nil,
        #     billing_address_5:                     nil,
        #     is_created_outside_franchise_category: false,
        #     has_available_forms:                   false,
        #     tags:                                  [],
        #     customfields:                          [],
        #     main_location:                         {
        #       id:                          7931612,
        #       company_id:                  114785,
        #       author_id:                   190917,
        #       object_id:                   7500746,
        #       object_type:                 'App\\Http\\Api\\Core\\Models\\BaseCustomer',
        #       title:                       'Main Location',
        #       address_1:                   '8144 Walnut Hill Lane',
        #       address_2:                   nil,
        #       city:                        'Dallas',
        #       state:                       'TX',
        #       zip_code:                    '75231',
        #       notes:                       nil,
        #       is_main_location:            true,
        #       created_at:                  '2024-09-12 19:31:12',
        #       updated_at:                  '2024-09-12 19:31:12',
        #       deleted_at:                  nil,
        #       location_coords:             { latitude: 32.8808555, longitude: -96.7662118 },
        #       order_index:                 1,
        #       is_primary_location:         true,
        #       primary_customer_contact_id: nil,
        #       search_text:                 "'75231':7 '8144':1 'dalla':5 'hill':3 'lane':4 'tx':6 'walnut':2",
        #       import_id:                   nil,
        #       address_3:                   nil,
        #       address_4:                   nil,
        #       address_5:                   nil,
        #       tax_rate:                    nil
        #     }
        #   }
        # }

        # call FieldPulse API for customers
        # fp_client.customers()
        #   (opt) limit: (Integer / default: Integrations::FieldPulse::V1::Base::IMPORT_BLOCK_COUNT)
        #   (opt) page:  (Integer / default: 1)
        #   (opt) search: (String / default: nil)
        def customers(**args)
          reset_attributes
          @result = {}
          page    = (args.dig(:page) || 1).to_i

          params = {
            limit: (args.dig(:limit) || Integrations::FieldPulse::V1::Base::IMPORT_BLOCK_COUNT).to_i,
            page:
          }
          params[:search] = args[:search] if args.dig(:search).present?

          fieldpulse_request(
            body:                  nil,
            error_message_prepend: 'Integrations::FieldPulse::V1::Customers.customers',
            method:                'get',
            params:,
            default_result:        @result,
            url:                   'customers'
          )

          @result
        end
        # example FieldPulse response
        # {
        #   error: false,
        #   response: [
        #     {
        #       id: 7500745,
        #       company_id: 114785,
        #       mongo_id: nil,
        #       email: 'johndoe82284923@gmail.com',
        #       phone: '214 888 8888',
        #       city: 'Dallas',
        #       state: 'TX',
        #       notes: nil,
        #       address_1: '4514 Travis Street',
        #       address_2: nil,
        #       cuid: 1001,
        #       first_name: 'John',
        #       middle_name: nil,
        #       last_name: 'Doe',
        #       company_name: nil,
        #       zip_code: '75204',
        #       searchable: nil,
        #       sort_key: nil,
        #       status: nil,
        #       has_different_billing_address: false,
        #       alt_email: nil,
        #       phone_e164: nil,
        #       qbo_id: nil,
        #       title: nil,
        #       suffix: nil,
        #       alt_phone: nil,
        #       billing_address_1: nil,
        #       billing_address_2: nil,
        #       billing_city: nil,
        #       billing_state: nil,
        #       fax: nil,
        #       skype: nil,
        #       assigned_to: nil,
        #       billing_zip_code: nil,
        #       secondary_first_name: nil,
        #       secondary_last_name: nil,
        #       secondary_email: nil,
        #       secondary_phone: nil,
        #       use_company_name: nil,
        #       dial_phone: nil,
        #       mobile_phone: nil,
        #       website: nil,
        #       qbo_sync_token: nil,
        #       last_qbo_sync: nil,
        #       created_at: '2024-09-12 19:31:12',
        #       updated_at: '2024-09-12 19:31:12',
        #       deleted_at: nil,
        #       parent_id: nil,
        #       postal_code: nil,
        #       alt_first_name: nil,
        #       alt_last_name: nil,
        #       lead_source: nil,
        #       service_address_1: nil,
        #       service_address_2: nil,
        #       service_address_city: nil,
        #       service_address_state: nil,
        #       service_address_zip_code: nil,
        #       job_notes: nil,
        #       account_type: 'individual',
        #       parent_id_previous: nil,
        #       address1: nil,
        #       xero_id: nil,
        #       is_sync: nil,
        #       notes_old: nil,
        #       different_billing_address: nil,
        #       xero_group_id: nil,
        #       dev_qbo: nil,
        #       source: nil,
        #       secondar_last_name: nil,
        #       sync_status: nil,
        #       xero_guid: nil,
        #       display_name: 'John Doe',
        #       uuid: '8a4b5de6-d237-4654-ac14-84ad8758c75e',
        #       xero_updated_date_utc: nil,
        #       country_code: nil,
        #       country_phone_code: nil,
        #       has_valid_phone: nil,
        #       alt_phone_e164: nil,
        #       secondary_phone_e164: nil,
        #       searchable_number: nil,
        #       phone_validation_message: nil,
        #       lead_source_id: nil,
        #       servicerocketpro_id: nil,
        #       service_titan_id: nil,
        #       pipeline_status_id: nil,
        #       next_steps: '',
        #       qbd_id: nil,
        #       qbd_edit_sequence: nil,
        #       merged_customer_id: nil,
        #       pipeline_status_updated_at: nil,
        #       mailchimp_contact_id: nil,
        #       is_tax_exempt: false,
        #       qbo_tax_exempt_reason: nil,
        #       search_text: "'doe':3 'john':2 'johndoe82284923@gmail.com':1",
        #       import_id: nil,
        #       qbd_fullname: nil,
        #       qbd_addr_company_name: false,
        #       qbd_addr_first_last_name: false,
        #       nicejob_id: nil,
        #       marketing360_id: nil,
        #       qbo_is_project: false,
        #       asset_display_settings: nil,
        #       next_sync_allowed_at: nil,
        #       sync_version: nil,
        #       job_display_settings: nil,
        #       default_invoice_due_date: nil,
        #       default_estimate_expiration_date: nil,
        #       is_phone_notification_subscribed: true,
        #       is_email_notification_subscribed: true,
        #       billing_address_3: nil,
        #       billing_address_4: nil,
        #       billing_address_5: nil,
        #       is_created_outside_franchise_category: false,
        #       tags: [],
        #       customfields: [],
        #       main_location: {
        #         id: 7931611,
        #         company_id: 114785,
        #         author_id: 190917,
        #         object_id: 7500745,
        #         object_type: 'App\\Http\\Api\\Core\\Models\\BaseCustomer',
        #         title: 'Main Location',
        #         address_1: '4514 Travis Street',
        #         address_2: nil,
        #         city: 'Dallas',
        #         state: 'TX',
        #         zip_code: '75204',
        #         notes: nil,
        #         s_main_location: true,
        #         created_at: '2024-09-12 19:31:12',
        #         updated_at: '2024-09-12 19:31:12',
        #         deleted_at: nil,
        #         location_coords: { latitude: 32.8223156, longitude: -96.7904375 },
        #         order_index: 1,
        #         is_primary_location: true,
        #         primary_customer_contact_id: nil,
        #         search_text: "'4514':1 '75204':6 'dalla':4 'street':3 'travi':2 'tx':5",
        #         import_id: nil,
        #         address_3: nil,
        #         address_4: nil,
        #         address_5: nil,
        #         tax_rate: nil
        #       }
        #     }, ...
        #   ]
        # }
      end
    end
  end
end
