# frozen_string_literal: true

# app/lib/integrations/field_pulse/v1/teams.rb
module Integrations
  module FieldPulse
    module V1
      module Teams
        # call FieldPulse API for teams
        # fp_client.teams
        def teams
          reset_attributes
          @result = {}
          teams   = []
          page    = 1

          loop do
            params = {
              limit: 100,
              page:
            }

            fieldpulse_request(
              body:                  nil,
              error_message_prepend: 'Integrations::FieldPulse::V1::Teams.teams',
              method:                'get',
              params:,
              default_result:        @result,
              url:                   'teams'
            )

            teams += @result.dig(:response) || []
            break if 1 == 1

            sleep_before_throttling(@result.dig(:extensions), @result.dig(:extensions, :cost, :actualQueryCost))
          end

          @result = teams.compact_blank
        end
        # example FieldPulse response
        # {
        #   error:    false,
        #   response: [
        #     { id:          130453,
        #       company_id:  114785,
        #       mongo_id:    nil,
        #       cuid:        1000,
        #       title:       'Default Team',
        #       author_id:   190917,
        #       description: nil,
        #       about:       'This is the default team for your company. You may choose to operate as one team or create multiple teams depending on your company structure.',
        #       created_at:  '2024-09-12 19:31:12',
        #       updated_at:  '2024-09-12 19:31:12',
        #       deleted_at:  nil,
        #       members:     [
        #         { id:                                                       190919,
        #           company_id:                                               114785,
        #           mongo_id:                                                 nil,
        #           cuid:                                                     1001,
        #           email:                                                    'taylor@chiirp.com',
        #           phone:                                                    '',
        #           notes:                                                    '',
        #           role:                                                     4,
        #           first_name:                                               'Taylor',
        #           last_name:                                                'Roberts',
        #           is_active:                                                true,
        #           notifications_alert_time:                                 nil,
        #           notifications_enabled_by_default:                         nil,
        #           notify_about_assigned_to_me:                              false,
        #           notify_about_upcoming_services:                           nil,
        #           send_new_password_email:                                  nil,
        #           google_maps:                                              nil,
        #           timesheets_enabled:                                       true,
        #           team_assigned_jobs_email_notification:                    false,
        #           team_upcoming_jobs_email_daily:                           false,
        #           team_upcoming_jobs_email_weekly:                          false,
        #           my_upcoming_jobs_email_daily:                             false,
        #           can_view_customer_list:                                   false,
        #           can_view_invoices:                                        false,
        #           can_view_timesheets:                                      nil,
        #           can_open_customer_profiles:                               true,
        #           can_create_cardpointe_payment:                            false,
        #           can_refund_cardpointe_payment:                            false,
        #           customer_communication_permission:                        0,
        #           my_assigned_jobs_notification:                            [1],
        #           clientsuccess_contact_id:                                 nil,
        #           avatar:                                                   nil,
        #           founder:                                                  false,
        #           recent_activity:                                          '2024-09-12 20:54:57',
        #           time_zone:                                                'America/Denver',
        #           last_known_location:                                      nil,
        #           invoicing_enabled:                                        true,
        #           newAdmin:                                                 false,
        #           created_at:                                               '2024-09-12 19:58:26',
        #           updated_at:                                               '2024-09-12 20:54:57',
        #           deleted_at:                                               nil,
        #           google_calendar_id:                                       '',
        #           my_assigned_projects_notification:                        [],
        #           my_assigned_subtasks_notification:                        [],
        #           my_primary_phone_number_notification:                     [2, 3],
        #           my_supervised_phone_numbers_notification:                 [2, 3],
        #           my_phone_numbers_notification:                            true,
        #           google_calendar_enabled:                                  false,
        #           google_calendar_object:                                   nil,
        #           notify_about_job_status_change_in_progress:               [],
        #           notify_about_job_status_change_pending:                   [],
        #           notify_about_job_status_change_completed:                 [],
        #           notify_about_invoice_status_change_paid:                  [],
        #           notify_about_customer_accepts_signature:                  [],
        #           notify_about_customer_rejects_signature:                  [],
        #           notify_about_estimate_invoice_email_opened:               [],
        #           notify_about_comment_added:                               [],
        #           my_reminder_notification:                                 [3],
        #           my_upcoming_jobs_email_weekly:                            false,
        #           can_view_leads:                                           false,
        #           webapp_sms_provider:                                      'sms',
        #           can_view_team_timesheets:                                 false,
        #           new_admin:                                                nil,
        #           invoice_list_permission:                                  2,
        #           stripe_user_pricing:                                      nil,
        #           primary_phone_number:                                     nil,
        #           supervised_phone_numbers:                                 nil,
        #           activecampaign_contact_id:                                nil,
        #           company_role:                                             nil,
        #           email_type:                                               nil,
        #           last_logged_in_at:                                        '2024-09-12 20:54:57',
        #           notificationsAlertTime:                                   nil,
        #           notificationsEnabledByDefault:                            nil,
        #           notifyAboutUpcomingServices:                              nil,
        #           phone_type:                                               nil,
        #           pipedrive_id:                                             nil,
        #           pipedrive_organization_id:                                nil,
        #           total_number_of_logins:                                   1,
        #           revoke_token:                                             false,
        #           is_calls_forwarded:                                       nil,
        #           my_upcoming_jobs_email:                                   nil,
        #           team_upcoming_jobs_email:                                 nil,
        #           calls_forwarded_phone_number:                             nil,
        #           calls_forwarded_phone_number_e164:                        nil,
        #           sandbox:                                                  nil,
        #           deactivated_at:                                           nil,
        #           is_pricebook_enabled:                                     false,
        #           can_view_projects:                                        false,
        #           inventory_hub_id:                                         nil,
        #           schedule_limitation:                                      'none',
        #           schedule_day_limitation:                                  0,
        #           is_master_company_admin:                                  false,
        #           is_free_user:                                             false,
        #           is_able_to_view_item_unit_cost:                           true,
        #           is_able_to_view_item_unit_price:                          true,
        #           is_able_to_create_item_template:                          true,
        #           api_token:                                                nil,
        #           link_group_id:                                            nil,
        #           customer_contact_details_limitation:                      'primary_contact',
        #           my_assigned_customers_notification:                       [],
        #           is_manual_timezone:                                       false,
        #           azuga_object:                                             nil,
        #           pricebook_show_li_in_groupings:                           true,
        #           is_able_to_create_subtasks_on_assigned_jobs:              false,
        #           is_able_to_edit_other_user_subtasks:                      false,
        #           is_able_to_see_jobs_assigned_to_other_users:              false,
        #           is_able_to_see_estimates_invoices_created_by_other_users: false,
        #           can_view_reporting:                                       false,
        #           is_able_to_view_to_contact_customer_from_mobile_app:      true,
        #           is_able_to_view_customer_contact_info:                    true,
        #           nicejob_id:                                               nil,
        #           can_view_updates:                                         true,
        #           sa_able_create_ma:                                        false,
        #           sa_able_see_ma_list:                                      false,
        #           sa_able_see_ma_on_custom_profiles:                        false,
        #           franchise_management_role:                                'none',
        #           is_item_list_visible:                                     false,
        #           tsheets_user_id:                                          nil,
        #           my_tagged_comments_notification:                          [],
        #           selected_pdf_invoice_type:                                nil,
        #           is_sa_able_to_create_jobs_assigned_to_himself:            false,
        #           can_see_subtasks_assigned_to_others:                      false,
        #           is_engage_available:                                      true,
        #           view_customer_list_mode:                                  nil,
        #           job_visibility:                                           3,
        #           notify_about_job_status_change_canceled:                  [],
        #           my_assigned_jobs_email_notification:                      true,
        #           pivot:                                                    { team_id: 130453, user_id: 190919 },
        #           settings:                                                 { avatar_color: '#007abe', webapp_top_header_color: '#000000', timesheet_hourly_cost_rate: '0', timesheet_hourly_billing_rate: '0', commission_rate: '' } },
        #         { id:                                                       190917,
        #           company_id:                                               114785,
        #           mongo_id:                                                 nil,
        #           cuid:                                                     1002,
        #           email:                                                    'kevin@chiirp.com',
        #           phone:                                                    '8023455136',
        #           notes:                                                    'The founding user',
        #           role:                                                     1,
        #           first_name:                                               'Kevin',
        #           last_name:                                                'Neubert',
        #           is_active:                                                true,
        #           notifications_alert_time:                                 nil,
        #           notifications_enabled_by_default:                         nil,
        #           notify_about_assigned_to_me:                              false,
        #           notify_about_upcoming_services:                           nil,
        #           send_new_password_email:                                  false,
        #           google_maps:                                              true,
        #           timesheets_enabled:                                       true,
        #           team_assigned_jobs_email_notification:                    true,
        #           team_upcoming_jobs_email_daily:                           true,
        #           team_upcoming_jobs_email_weekly:                          false,
        #           my_upcoming_jobs_email_daily:                             true,
        #           can_view_customer_list:                                   true,
        #           can_view_invoices:                                        true,
        #           can_view_timesheets:                                      nil,
        #           can_open_customer_profiles:                               true,
        #           can_create_cardpointe_payment:                            false,
        #           can_refund_cardpointe_payment:                            false,
        #           customer_communication_permission:                        0,
        #           my_assigned_jobs_notification:                            [],
        #           clientsuccess_contact_id:                                 nil,
        #           avatar:                                                   { url: 'https://cdn.fieldpulse.com/apiCloud/lvpk/avatars/190917-240920014415.png', file_name: '190917-240920014415.png' },
        #           founder:                                                  true,
        #           recent_activity:                                          '2024-09-20 13:42:06',
        #           time_zone:                                                'America/New_York',
        #           last_known_location:                                      nil,
        #           invoicing_enabled:                                        true,
        #           newAdmin:                                                 false,
        #           created_at:                                               '2024-09-12 19:31:12',
        #           updated_at:                                               '2024-09-23 16:04:08',
        #           deleted_at:                                               nil,
        #           google_calendar_id:                                       'primary',
        #           my_assigned_projects_notification:                        [],
        #           my_assigned_subtasks_notification:                        [],
        #           my_primary_phone_number_notification:                     [2, 3],
        #           my_supervised_phone_numbers_notification:                 [2, 3],
        #           my_phone_numbers_notification:                            true,
        #           google_calendar_enabled:                                  false,
        #           google_calendar_object:                                   nil,
        #           notify_about_job_status_change_in_progress:               [],
        #           notify_about_job_status_change_pending:                   [],
        #           notify_about_job_status_change_completed:                 [],
        #           notify_about_invoice_status_change_paid:                  [],
        #           notify_about_customer_accepts_signature:                  [],
        #           notify_about_customer_rejects_signature:                  [],
        #           notify_about_estimate_invoice_email_opened:               [],
        #           notify_about_comment_added:                               [],
        #           my_reminder_notification:                                 [3],
        #           my_upcoming_jobs_email_weekly:                            false,
        #           can_view_leads:                                           true,
        #           webapp_sms_provider:                                      'sms',
        #           can_view_team_timesheets:                                 true,
        #           new_admin:                                                true,
        #           invoice_list_permission:                                  1,
        #           stripe_user_pricing:                                      nil,
        #           primary_phone_number:                                     nil,
        #           supervised_phone_numbers:                                 nil,
        #           activecampaign_contact_id:                                nil,
        #           company_role:                                             'owner',
        #           email_type:                                               nil,
        #           last_logged_in_at:                                        '2024-09-20 13:42:06',
        #           notificationsAlertTime:                                   30,
        #           notificationsEnabledByDefault:                            true,
        #           notifyAboutUpcomingServices:                              true,
        #           phone_type:                                               nil,
        #           pipedrive_id:                                             nil,
        #           pipedrive_organization_id:                                nil,
        #           total_number_of_logins:                                   2,
        #           revoke_token:                                             false,
        #           is_calls_forwarded:                                       false,
        #           my_upcoming_jobs_email:                                   nil,
        #           team_upcoming_jobs_email:                                 nil,
        #           calls_forwarded_phone_number:                             nil,
        #           calls_forwarded_phone_number_e164:                        nil,
        #           sandbox:                                                  nil,
        #           deactivated_at:                                           nil,
        #           is_pricebook_enabled:                                     false,
        #           can_view_projects:                                        true,
        #           inventory_hub_id:                                         nil,
        #           schedule_limitation:                                      'none',
        #           schedule_day_limitation:                                  1,
        #           is_master_company_admin:                                  false,
        #           is_free_user:                                             true,
        #           is_able_to_view_item_unit_cost:                           true,
        #           is_able_to_view_item_unit_price:                          true,
        #           is_able_to_create_item_template:                          true,
        #           api_token:                                                '45dBG6ei552e2ysg1B21t6HcFSHYSK604rm7dvfL',
        #           link_group_id:                                            nil,
        #           customer_contact_details_limitation:                      'primary_contact',
        #           my_assigned_customers_notification:                       [],
        #           is_manual_timezone:                                       false,
        #           azuga_object:                                             nil,
        #           pricebook_show_li_in_groupings:                           true,
        #           is_able_to_create_subtasks_on_assigned_jobs:              false,
        #           is_able_to_edit_other_user_subtasks:                      false,
        #           is_able_to_see_jobs_assigned_to_other_users:              false,
        #           is_able_to_see_estimates_invoices_created_by_other_users: false,
        #           can_view_reporting:                                       false,
        #           is_able_to_view_to_contact_customer_from_mobile_app:      true,
        #           is_able_to_view_customer_contact_info:                    true,
        #           nicejob_id:                                               nil,
        #           can_view_updates:                                         true,
        #           sa_able_create_ma:                                        false,
        #           sa_able_see_ma_list:                                      false,
        #           sa_able_see_ma_on_custom_profiles:                        false,
        #           franchise_management_role:                                'none',
        #           is_item_list_visible:                                     false,
        #           tsheets_user_id:                                          nil,
        #           my_tagged_comments_notification:                          [1, 2, 3],
        #           selected_pdf_invoice_type:                                nil,
        #           is_sa_able_to_create_jobs_assigned_to_himself:            false,
        #           can_see_subtasks_assigned_to_others:                      true,
        #           is_engage_available:                                      true,
        #           view_customer_list_mode:                                  nil,
        #           job_visibility:                                           3,
        #           notify_about_job_status_change_canceled:                  [],
        #           my_assigned_jobs_email_notification:                      false,
        #           pivot:                                                    { team_id: 130453, user_id: 190917 },
        #           settings:                                                 { avatar_color: '#ff8800', webapp_top_header_color: '#000000', timesheet_hourly_cost_rate: '0', timesheet_hourly_billing_rate: '0', commission_rate: '' } }
        #       ],
        #       managers:    [
        #         { id:                                                       190917,
        #           company_id:                                               114785,
        #           mongo_id:                                                 nil,
        #           cuid:                                                     1002,
        #           email:                                                    'kevin@chiirp.com',
        #           phone:                                                    '8023455136',
        #           notes:                                                    'The founding user',
        #           role:                                                     1,
        #           first_name:                                               'Kevin',
        #           last_name:                                                'Neubert',
        #           is_active:                                                true,
        #           notifications_alert_time:                                 nil,
        #           notifications_enabled_by_default:                         nil,
        #           notify_about_assigned_to_me:                              false,
        #           notify_about_upcoming_services:                           nil,
        #           send_new_password_email:                                  false,
        #           google_maps:                                              true,
        #           timesheets_enabled:                                       true,
        #           team_assigned_jobs_email_notification:                    true,
        #           team_upcoming_jobs_email_daily:                           true,
        #           team_upcoming_jobs_email_weekly:                          false,
        #           my_upcoming_jobs_email_daily:                             true,
        #           can_view_customer_list:                                   true,
        #           can_view_invoices:                                        true,
        #           can_view_timesheets:                                      nil,
        #           can_open_customer_profiles:                               true,
        #           can_create_cardpointe_payment:                            false,
        #           can_refund_cardpointe_payment:                            false,
        #           customer_communication_permission:                        0,
        #           my_assigned_jobs_notification:                            [],
        #           clientsuccess_contact_id:                                 nil,
        #           avatar:                                                   { url: 'https://cdn.fieldpulse.com/apiCloud/lvpk/avatars/190917-240920014415.png', file_name: '190917-240920014415.png' },
        #           founder:                                                  true,
        #           recent_activity:                                          '2024-09-20 13:42:06',
        #           time_zone:                                                'America/New_York',
        #           last_known_location:                                      nil,
        #           invoicing_enabled:                                        true,
        #           newAdmin:                                                 false,
        #           created_at:                                               '2024-09-12 19:31:12',
        #           updated_at:                                               '2024-09-23 16:04:08',
        #           deleted_at:                                               nil,
        #           google_calendar_id:                                       'primary',
        #           my_assigned_projects_notification:                        [],
        #           my_assigned_subtasks_notification:                        [],
        #           my_primary_phone_number_notification:                     [2, 3],
        #           my_supervised_phone_numbers_notification:                 [2, 3],
        #           my_phone_numbers_notification:                            true,
        #           google_calendar_enabled:                                  false,
        #           google_calendar_object:                                   nil,
        #           notify_about_job_status_change_in_progress:               [],
        #           notify_about_job_status_change_pending:                   [],
        #           notify_about_job_status_change_completed:                 [],
        #           notify_about_invoice_status_change_paid:                  [],
        #           notify_about_customer_accepts_signature:                  [],
        #           notify_about_customer_rejects_signature:                  [],
        #           notify_about_estimate_invoice_email_opened:               [],
        #           notify_about_comment_added:                               [],
        #           my_reminder_notification:                                 [3],
        #           my_upcoming_jobs_email_weekly:                            false,
        #           can_view_leads:                                           true,
        #           webapp_sms_provider:                                      'sms',
        #           can_view_team_timesheets:                                 true,
        #           new_admin:                                                true,
        #           invoice_list_permission:                                  1,
        #           stripe_user_pricing:                                      nil,
        #           primary_phone_number:                                     nil,
        #           supervised_phone_numbers:                                 nil,
        #           activecampaign_contact_id:                                nil,
        #           company_role:                                             'owner',
        #           email_type:                                               nil,
        #           last_logged_in_at:                                        '2024-09-20 13:42:06',
        #           notificationsAlertTime:                                   30,
        #           notificationsEnabledByDefault:                            true,
        #           notifyAboutUpcomingServices:                              true,
        #           phone_type:                                               nil,
        #           pipedrive_id:                                             nil,
        #           pipedrive_organization_id:                                nil,
        #           total_number_of_logins:                                   2,
        #           revoke_token:                                             false,
        #           is_calls_forwarded:                                       false,
        #           my_upcoming_jobs_email:                                   nil,
        #           team_upcoming_jobs_email:                                 nil,
        #           calls_forwarded_phone_number:                             nil,
        #           calls_forwarded_phone_number_e164:                        nil,
        #           sandbox:                                                  nil,
        #           deactivated_at:                                           nil,
        #           is_pricebook_enabled:                                     false,
        #           can_view_projects:                                        true,
        #           inventory_hub_id:                                         nil,
        #           schedule_limitation:                                      'none',
        #           schedule_day_limitation:                                  1,
        #           is_master_company_admin:                                  false,
        #           is_free_user:                                             true,
        #           is_able_to_view_item_unit_cost:                           true,
        #           is_able_to_view_item_unit_price:                          true,
        #           is_able_to_create_item_template:                          true,
        #           api_token:                                                '45dBG6ei552e2ysg1B21t6HcFSHYSK604rm7dvfL',
        #           link_group_id:                                            nil,
        #           customer_contact_details_limitation:                      'primary_contact',
        #           my_assigned_customers_notification:                       [],
        #           is_manual_timezone:                                       false,
        #           azuga_object:                                             nil,
        #           pricebook_show_li_in_groupings:                           true,
        #           is_able_to_create_subtasks_on_assigned_jobs:              false,
        #           is_able_to_edit_other_user_subtasks:                      false,
        #           is_able_to_see_jobs_assigned_to_other_users:              false,
        #           is_able_to_see_estimates_invoices_created_by_other_users: false,
        #           can_view_reporting:                                       false,
        #           is_able_to_view_to_contact_customer_from_mobile_app:      true,
        #           is_able_to_view_customer_contact_info:                    true,
        #           nicejob_id:                                               nil,
        #           can_view_updates:                                         true,
        #           sa_able_create_ma:                                        false,
        #           sa_able_see_ma_list:                                      false,
        #           sa_able_see_ma_on_custom_profiles:                        false,
        #           franchise_management_role:                                'none',
        #           is_item_list_visible:                                     false,
        #           tsheets_user_id:                                          nil,
        #           my_tagged_comments_notification:                          [1, 2, 3],
        #           selected_pdf_invoice_type:                                nil,
        #           is_sa_able_to_create_jobs_assigned_to_himself:            false,
        #           can_see_subtasks_assigned_to_others:                      true,
        #           is_engage_available:                                      true,
        #           view_customer_list_mode:                                  nil,
        #           job_visibility:                                           3,
        #           notify_about_job_status_change_canceled:                  [],
        #           my_assigned_jobs_email_notification:                      false,
        #           pivot:                                                    { team_id: 130453, user_id: 190917 } }
        #       ] }
        #   ]
        # }
      end
    end
  end
end
