# erb-lint custom config file
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
EnableDefaultLinters: true
linters:
  FinalNewline:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      # Enabling this adds a frozen string literal magic comment to every block.
      Style/FrozenStringLiteralComment:
        Enabled: false
      # erb_lint reports errors with this cop.
      Style/MultilineTernaryOperator:
        Enabled: false
      # Empty blocks have utility in views, e.g. for resetting content_for and
      # rendering slots without args.
      Lint/EmptyBlock:
        Enabled: false
      Lint/MissingCopEnableDirective:
        Enabled: false
      Lint/RedundantCopEnableDirective:
        Enabled: false
      # False flags for view files. ViewComponents should never see this, though, as they should never need to assign in a view.
      Lint/UselessAssignment:
        Exclude:
          - "app/views/**/*"
      Rails/OutputSafety:
        Enabled: false
  SpaceAroundErbTag:
    enabled: true
