services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.development
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - .:/usr/src/app
  #   command: bundle exec puma -C config/puma.rb
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  db:
    image: postgres:16.3
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: funyl_development
      POSTGRES_USER: chiirp_test
      POSTGRES_PASSWORD: 9Y07yd6hGSGFWq3rzUeJVUHXA9yzZ82m

  redis:
    image: redis:7.2.3
    ports:
      - 6379:6379

volumes:
  db_data:
